[package]
name = "blockchain"
version = "0.1.0"
edition = "2018"

[dependencies]
solana-client = "1.18.26"
solana-sdk = "1.18.26"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

